*Artificial* Neural Network

Importing the Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.7.0'

Part 1 - Data Preprocessing

In [ ]:
dataset = pd.read_csv('/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values #creating matrix of features x
y = dataset.iloc[:, -1].values #creating dependent var vector y

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


We would've had to deal with missing data, but this dataset doesn't have missing so we are good on that front.

# Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2]) # accessing the gender column of matrix of features x

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
#one hot encoding -- did well! -- dummy variables replaced (France --1.0, 0.0, 0.0)

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
print(X_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [ ]:
print(y_train)

[0 0 0 ... 0 0 1]


In [ ]:
print(y_test)

[0 1 0 ... 0 0 0]


Feature Scaling -- VERY IMPORTANT for ALL FEATURES

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building the ANN

Compiling the ANN

Initializing the ANN (as a sequence of layers)

In [ ]:
# object of the sequential class
# as an instance of the sequence of layers
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [ ]:
#use the dense class
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

neuron neuron neuron -- all of these are units -- specify how many neurons you want.
hyper-parameters -- are just picked - randomly
building a shallow neural network

Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the output layer

In [ ]:
#we only need one neuron
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
#for classification, you would use the 'softmax' activation function

if output has three classes, ABC
output neurons -- to one-hot-encode the neurons
ABC -- A: 1.0 0.0 0.0, B: 0.0 1.0 0.0, C: 0.0 0.0 1.0 (three neurons)

# Training the ANN

Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
#binary classification --> use 'binary_cross_entropy'
#here you would enter 'categorical_cross_entropy'

Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
#default is 32 - hyperparameters get batch learning

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5836 - accuracy: 0.7205
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4654 - accuracy: 0.8014
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4263 - accuracy: 0.8200
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4043 - accuracy: 0.8349
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3893 - accuracy: 0.8441
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3774 - accuracy: 0.8469
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3685 - accuracy: 0.8509
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3627 - accuracy: 0.8528
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3585 - accuracy: 0.8560
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3552 - accura

# Making the predictions and evaluating the model

Predicting the result of a single observation

**Homework**
Use our ANN model to predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40 years old
Tenure: 3 years
Balance: 60000
Number of Products: 2
Does this customer have a credit card? Yes
Is this cusomter an Active Member: Yes
Estimated Salary: 50000
So, should we say goodbye to that customer?

In [ ]:
# remember these things:
prediction = ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
#scale that single observation if it was scaled when trained
print(prediction)

[[0.03362074]]


In [ ]:
if prediction[0][0] < 0.5:
  print("Customer stays in the bank!")
else:
  print("Customer leaves the bank!")

Customer stays in the bank!


Important 1: Notice that the values of the features were all input in a double pair of square brackets. That's becuase the 'predict' method always xpects a 2D array as the format for its inputs. And putting our values into a double pair of square brackets makes the input exactl a 2D array.

Important 2: Notice also that the 'France' country was not input as a string in the last column but as a "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded into "1,0,0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1532   63]
 [ 209  196]]


0.864

Apply this for another binary outcome predictor!!