# Let's Predict Diabetes

Importing libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

Data Preprocessing

In [ ]:
dataset = pd.read_csv('/content/diabetes.csv')
X = dataset.iloc[:, :-1].values #creating matrix of features x
y = dataset.iloc[:, -1].values #creating dependent var vector y

In [ ]:
print(X)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


In [ ]:
print(y)

[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1
 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1
 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1
 0 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1
 1 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 0)

In [ ]:
print(X_train)

[[7.00e+00 1.50e+02 7.80e+01 ... 3.52e+01 6.92e-01 5.40e+01]
 [4.00e+00 9.70e+01 6.00e+01 ... 2.82e+01 4.43e-01 2.20e+01]
 [0.00e+00 1.65e+02 9.00e+01 ... 5.23e+01 4.27e-01 2.30e+01]
 ...
 [4.00e+00 9.40e+01 6.50e+01 ... 2.47e+01 1.48e-01 2.10e+01]
 [1.10e+01 8.50e+01 7.40e+01 ... 3.01e+01 3.00e-01 3.50e+01]
 [5.00e+00 1.36e+02 8.20e+01 ... 0.00e+00 6.40e-01 6.90e+01]]


In [ ]:
print(X_test)

[[1.000e+00 1.990e+02 7.600e+01 ... 4.290e+01 1.394e+00 2.200e+01]
 [2.000e+00 1.070e+02 7.400e+01 ... 3.360e+01 4.040e-01 2.300e+01]
 [4.000e+00 7.600e+01 6.200e+01 ... 3.400e+01 3.910e-01 2.500e+01]
 ...
 [4.000e+00 1.420e+02 8.600e+01 ... 4.400e+01 6.450e-01 2.200e+01]
 [3.000e+00 1.160e+02 7.400e+01 ... 2.630e+01 1.070e-01 2.400e+01]
 [1.000e+00 1.070e+02 7.200e+01 ... 3.080e+01 8.210e-01 2.400e+01]]


In [ ]:
print(y_train)

[1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 1 1 1 0 0
 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1 1
 0 0 0 1 0 0 1 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1
 0 1 1 1 1 0 0 0 0 1 1 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1
 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1
 0 0 0 0 1 1 0 0 0 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1
 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 1 0 1 1 1 1 0 1 1 0 0 1 1 0 0 1 1
 0 0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1
 1 0 1 0 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 1 1
 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 1
 1 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 1 1 1 1 0 1 0 0 0 0 0 1
 0 1 0 1 0 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0
 1 0 0 0 1 0 0 0 0 0 0 1 

In [ ]:
print(y_test)

[1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 1 0
 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 1 0 0 0
 0 1 0 1 0 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
diabetes_classifier = tf.keras.models.Sequential()

In [ ]:
diabetes_classifier.add(tf.keras.layers.Dense(units=8, activation='relu'))

In [ ]:
diabetes_classifier.add(tf.keras.layers.Dense(units=8, activation='relu'))

In [ ]:
diabetes_classifier.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
diabetes_classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
diabetes_classifier.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.6462 - accuracy: 0.6303
Epoch 2/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6232 - accuracy: 0.6726
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6024 - accuracy: 0.6824
Epoch 4/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5843 - accuracy: 0.7003
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5683 - accuracy: 0.7117
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5552 - accuracy: 0.7134
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5435 - accuracy: 0.7150
Epoch 8/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5339 - accuracy: 0.7329
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5252 - accuracy: 0.7394
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5194 - accuracy: 0.7459
Epoch 11/

In [ ]:
prediction = diabetes_classifier.predict(sc.transform([[7, 158, 72, 35, 168, 32.5, 0.627, 52]]))
if prediction[0][0] >= 0.5:
  print("Unfortunately, there is a high chance the patient has diabetes.")
else:
  print("Thankfully, diabetes is not a problem at the moment for this patient.")

Unfortunately, there is a high chance the patient has diabetes.


In [ ]:
prediction = diabetes_classifier.predict(sc.transform([[10, 138, 80, 0, 0, 27.5, 0.627, 52]]))
if prediction[0][0] >= 0.5:
  print("Unfortunately, there is a high chance the patient has diabetes.")
else:
  print("Thankfully, diabetes is not a problem at the moment for this patient.")

Thankfully, diabetes is not a problem at the moment for this patient.


In [ ]:
prediction = diabetes_classifier.predict(sc.transform([[0, 138, 96, 0, 0, 27.5, 0.127, 23]]))
if prediction[0][0] >= 0.5:
  print("Unfortunately, there is a high chance the patient has diabetes.")
else:
  print("Thankfully, diabetes is not a problem at the moment for this patient.")

Thankfully, diabetes is not a problem at the moment for this patient.


In [ ]:
!pip install streamlit

     |████████████████████████████████| 9.9 MB 8.6 MB/s 
     |████████████████████████████████| 164 kB 71.5 MB/s 
     |████████████████████████████████| 181 kB 29.5 MB/s 
     |████████████████████████████████| 76 kB 3.7 MB/s 
     |████████████████████████████████| 4.3 MB 55.5 MB/s 
     |████████████████████████████████| 111 kB 19.5 MB/s 
     |████████████████████████████████| 63 kB 1.4 MB/s 
     |████████████████████████████████| 130 kB 28.0 MB/s 
     |████████████████████████████████| 793 kB 25.4 MB/s 
     |████████████████████████████████| 380 kB 51.6 MB/s 
  Created wheel for blinker: filename=blinker-1.4-py3-none-any.whl size=13478 sha256=e9c9eeab4c516f6bac1aacd236a4d8c14b9af29d75fc82a7eadf2fc113e55a4b
  Stored in directory: /root/.cache/pip/wheels/22/f5/18/df711b66eb25b21325c132757d4314db9ac5e8dabeaf196eab
Successfully built blinker
  Attempting uninstall: prompt-toolkit
    Found existing installation: prompt-toolkit 1.0.18
    Uninstalling prompt-toolkit-1.0.18:
      S

In [ ]:
#!pip install pyngrok

In [ ]:
%%writefile lpd_main.py
import streamlit as st

PAGE_CONFIG = {"page_title":"StColab.io","page_icon":":smiley:","layout":"centered"}
st.set_page_config(**PAGE_CONFIG)
def main():
	st.title("Awesome Streamlit for ML")
	st.subheader("How to run streamlit from colab")
	menu = ["Home","About"]
	choice = st.sidebar.selectbox('Menu',menu)
	if choice == 'Home':
		st.subheader("Streamlit From Colab")
if __name__ == '__main__':
	main()


header = st.container()
dataset = st.container()
features = st.container()
model_training = st.container()

with header:
	st.title("Let's explore diabetes")
	st.text("It's very important to know about the possibility of having diabetes")
	#st.text(prediction)
	st.text(prediction[0][0])

with dataset:
	st.header("Here's the dataset we'll be using to test our data.")
	#st.write(dataset.head())

	#pat_age = pd.DataFrame(dataset['Age'].value_counts())
	#st.bar_chart(pat_age)


Overwriting lpd_main.py


In [ ]:
#!ls

In [ ]:
#!ngrok authtoken 22YtnGSQvQNRDngacW3ytwu04Z8_6HiJoYzhmbvLQXXiFrnrb

In [ ]:
#!ngrok

In [ ]:
#from pyngrok import ngrok

In [ ]:
#!streamlit run lpd_main.py&>/dev/null&

In [ ]:
#publ_url = ngrok.connect(port='8501')

In [ ]:
#!pgrep streamlit

In [ ]:
#publ_url

In [ ]:
#!streamlit run --server.port 80 lpd_main.py >/dev/null
#!streamlit run --server.port 80 lpd_main.py
! streamlit run lpd_main.py & npx localtunnel --port 8501